# Generated by Django 5.2.2 on 2025-06-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='created_datetime',
            field=models.DateField(),
        ),
    ]
