POST http://localhost:8000/careers/
Content-Type: application/json

{
  "username": "Arthur",
  "title": "Backend Developer",
  "created_datetime": "2025-06-07",
  "content": "Python"
}

###

GET http://localhost:8000/careers/
Content-Type: application/json


### Patch valid 

PATCH http://localhost:8000/careers/3/
Content-Type: application/json

{
  "title": "Software enginner",
  "content": "Python"
}

### Patch invalid

PATCH http://localhost:8000/careers/3/
Content-Type: application/json

{
  "created_datetime": "2025-05-04",
  "title": "Software enginner",
  "content": "Python"
}

###

DELETE http://localhost:8000/careers/4/
Content-Type: application/json
